Python 3 compatibility
zopefoundation/grokcore.content pull request #3
Opened 2016-07-13 14:19 UTC by sallner

According to https://zope3.pov.lt/py3/ this package blocks at least three grok packages on their way to Python 3. In principal the use of `zope.interface.implements` had to be changed to the `zope.interface.implementer` decorator. I also added tox and coverage to the project to successfully port it to Python 3.

@thefunny42 : It would be nice, if you could review the PR, merge and release it, so that the new version can be used as soon as possible for further porting to Python 3.

2016-09-28 12:15 UTC, janwijbrand requested changes
I'd like to see the additional comment on the trick used in the test to have the elipsis work. Oher than that, LGTM.

2016-09-28 12:15 UTC, janwijbrand commented on src/grokcore/content/tests/test_container.py
> +    >>> 'skull name';skull.__name__
After talking face2face about this, I understand what this is for, but perhaps you can leave a comment about this trick?

2016-09-28 12:17 UTC, janwijbrand approved these changes
Ok, we added the comment. We'll merge it.

2016-09-28 12:25 UTC, merged

2016-09-29 06:49 UTC, icemac commented on src/grokcore/content/tests/test_container.py
> +    >>> 'skull name';skull.__name__
What about `str(skull.__name__)` this has the same `repr` in Python 2 and 3 of `'skull'`.